services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.3
    container_name: bench_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: benchmark
      CLICKHOUSE_PASSWORD: benchmark123
      CLICKHOUSE_DB: benchmark
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    container_name: bench_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  clickhouse_data:
  es_data: